#!/bin/zsh

git submodule init && git submodule update
rake jekyll:compile
git checkout gh-pages

sleep 2

rm -rf !("_site"|"CNAME")
cp -R _site/* .
rm -rf _site
git commit -a -m $1
git push origin gh-pages
git checkout master